<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-11T08:28:12 ICT" name="Suite" finished-at="2025-03-11T08:31:29 ICT" duration-ms="197062">
    <groups>
    </groups>
    <test started-at="2025-03-11T08:28:12 ICT" name="Test_Shopee" finished-at="2025-03-11T08:31:29 ICT" duration-ms="197062">
      <class name="TestCase.TestCaseLogin">
        <test-method is-config="true" signature="SetUp()[pri:0, instance:TestCase.TestCaseLogin@f09733f]" started-at="2025-03-11T08:28:12 ICT" name="SetUp" finished-at="2025-03-11T08:29:04 ICT" duration-ms="52814" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="TestLoginWithPhoneNumber(java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:TestCase.TestCaseLogin@f09733f]" started-at="2025-03-11T08:29:05 ICT" name="TestLoginWithPhoneNumber" description="TC01 - Kiểm tra đăng nhập thành công bằng số điện thoại" data-provider="ValidLoginData1" finished-at="2025-03-11T08:29:20 ICT" duration-ms="15371" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[346991600]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Quang0511@]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[0346991600quang]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLoginWithPhoneNumber -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:TestCase.TestCaseLogin@f09733f]" started-at="2025-03-11T08:29:21 ICT" name="TearDown" finished-at="2025-03-11T08:29:24 ICT" duration-ms="2705" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="SetUp()[pri:0, instance:TestCase.TestCaseLogin@f09733f]" started-at="2025-03-11T08:29:24 ICT" name="SetUp" finished-at="2025-03-11T08:29:54 ICT" duration-ms="29770" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="TestLoginWithEmail(java.lang.String,java.lang.String,java.lang.String)[pri:2, instance:TestCase.TestCaseLogin@f09733f]" started-at="2025-03-11T08:29:54 ICT" name="TestLoginWithEmail" description="TC01 - Kiểm tra đăng nhập thành công bằng gmail" data-provider="ValidLoginData2" finished-at="2025-03-11T08:30:08 ICT" duration-ms="14555" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[toilaquang6@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Quang0511@]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[0346991600quang]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLoginWithEmail -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:TestCase.TestCaseLogin@f09733f]" started-at="2025-03-11T08:30:09 ICT" name="TearDown" finished-at="2025-03-11T08:30:12 ICT" duration-ms="2613" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="SetUp()[pri:0, instance:TestCase.TestCaseLogin@f09733f]" started-at="2025-03-11T08:30:12 ICT" name="SetUp" finished-at="2025-03-11T08:30:41 ICT" duration-ms="29765" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="TestLoginFail(java.lang.String,java.lang.String,java.lang.String)[pri:3, instance:TestCase.TestCaseLogin@f09733f]" started-at="2025-03-11T08:30:41 ICT" name="TestLoginFail" description="TC02 - Kiểm tra đăng nhập thất bại" data-provider="InvalidLoginData1" finished-at="2025-03-11T08:30:47 ICT" duration-ms="5671" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[983495935]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[UKsjsdW@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[TĂ i khoáº£n hoáº·c máº­t kháº©u Ä‘Äƒng nháº­p khĂ´ng chĂ­nh xĂ¡c. Vui lĂ²ng thá»­ láº¡i.]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Thông báo lỗi không khớp.Mong đợi: TĂ i khoáº£n hoáº·c máº­t kháº©u Ä‘Äƒng nháº­p khĂ´ng chĂ­nh xĂ¡c. Vui lĂ²ng thá»­ láº¡i. | Thực tế: Tài khoản hoặc mật khẩu đăng nhập không chính xác. Vui lòng thử lại.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Thông báo lỗi không khớp.Mong đợi: TĂ i khoáº£n hoáº·c máº­t kháº©u Ä‘Äƒng nháº­p khĂ´ng chĂ­nh xĂ¡c. Vui lĂ²ng thá»­ láº¡i. | Thực tế: Tài khoản hoặc mật khẩu đăng nhập không chính xác. Vui lòng thử lại.
at Page.LoginPage.lambda$confirmLoginFaild$1(LoginPage.java:132)
at io.qameta.allure.Allure.lambda$step$1(Allure.java:127)
at io.qameta.allure.Allure.step(Allure.java:181)
at io.qameta.allure.Allure.step(Allure.java:125)
at Page.LoginPage.confirmLoginFaild(LoginPage.java:119)
at TestCase.TestCaseLogin.TestLoginFail(TestCaseLogin.java:151)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLoginFail -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:TestCase.TestCaseLogin@f09733f]" started-at="2025-03-11T08:30:48 ICT" name="TearDown" finished-at="2025-03-11T08:30:50 ICT" duration-ms="2640" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="SetUp()[pri:0, instance:TestCase.TestCaseLogin@f09733f]" started-at="2025-03-11T08:30:50 ICT" name="SetUp" finished-at="2025-03-11T08:31:17 ICT" duration-ms="26823" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="TestLoginFail_AccountLengthLessThan8(java.lang.String,java.lang.String,java.lang.String)[pri:4, instance:TestCase.TestCaseLogin@f09733f]" started-at="2025-03-11T08:31:17 ICT" name="TestLoginFail_AccountLengthLessThan8" description="TC03 - Kiểm tra đăng nhập thất bại với tài khoản &lt; 9 kí tự" data-provider="InvalidLoginData2" finished-at="2025-03-11T08:31:23 ICT" duration-ms="6257" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[8453234]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[UKsjsdW@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Uiiii, cĂ³ lá»—i rá»“i. Vui lĂ²ng thá»­ láº¡i sau]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Thông báo lỗi không khớp.Mong đợi: Uiiii, cĂ³ lá»—i rá»“i. Vui lĂ²ng thá»­ láº¡i sau | Thực tế: Uiiii, có lỗi rồi. Vui lòng thử lại sau]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Thông báo lỗi không khớp.Mong đợi: Uiiii, cĂ³ lá»—i rá»“i. Vui lĂ²ng thá»­ láº¡i sau | Thực tế: Uiiii, có lỗi rồi. Vui lòng thử lại sau
at Page.LoginPage.lambda$confirmLoginFaild$1(LoginPage.java:132)
at io.qameta.allure.Allure.lambda$step$1(Allure.java:127)
at io.qameta.allure.Allure.step(Allure.java:181)
at io.qameta.allure.Allure.step(Allure.java:125)
at Page.LoginPage.confirmLoginFaild(LoginPage.java:119)
at TestCase.TestCaseLogin.TestLoginFail_AccountLengthLessThan8(TestCaseLogin.java:171)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLoginFail_AccountLengthLessThan8 -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:TestCase.TestCaseLogin@f09733f]" started-at="2025-03-11T08:31:24 ICT" name="TearDown" finished-at="2025-03-11T08:31:27 ICT" duration-ms="2654" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:TestCase.TestCaseLogin@f09733f]" started-at="2025-03-11T08:31:27 ICT" name="afterClass" finished-at="2025-03-11T08:31:29 ICT" duration-ms="2021" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- TestCase.TestCaseLogin -->
    </test> <!-- Test_Shopee -->
  </suite> <!-- Suite -->
</testng-results>
